spring:
  application:
    name: jp-cloud-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  main:
    web-application-type: reactive
server:
  port: 8080

eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka